# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 194636f4d9c99c026fd5383ae02942a1780dff0a54b3af68ab39558a98baf8d6f6332d323d88f529780fd3109693aec64a7a648bf180ef9663b22cb4cbf8962e

test:
  secret_key_base: 2a705c58f184d9f2c9369429455448f46a28639e60507a66d045142bffd8408b2a3e6ecb99e5a3e2c209c11da6e8e0f0456de1390ee3e4c68424eea8a37e7a55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
